# The generated header is the authority for the DLL's public C entry points.
file(STRINGS "${HEADER}" declarations REGEX "^WGPU_EXPORT .* wgpu[A-Za-z0-9_]+\\(")
if(NOT declarations)
    message(FATAL_ERROR "No WebGPU exports found in ${HEADER}")
endif()
set(exports "")
foreach(declaration IN LISTS declarations)
    string(REGEX MATCH " (wgpu[A-Za-z0-9_]+)\\(" match "${declaration}")
    list(APPEND exports "${CMAKE_MATCH_1}")
endforeach()
list(REMOVE_DUPLICATES exports)
list(SORT exports)
string(JOIN "\n    " symbols ${exports})
file(WRITE "${OUTPUT}" "LIBRARY webgpu_dawn\nEXPORTS\n    ${symbols}\n")
